language: java
jdk: openjdk11
sudo: false
script:
- bash gradlew displayCommitHash
- bash gradlew isCI
- bash gradlew buildPlugin
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
