language: java
jdk: oraclejdk8
sudo: false
script:
- jdk_switcher use oraclejdk8
- bash gradlew displayCommitHash
- bash gradlew isCI
- bash gradlew buildPlugin
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
