language: java
jdk:
- oraclejdk8
script:
- bash gradlew displayCommitHash
- bash gradlew isCI
- bash gradlew buildPlugin
before_install:
- chmod a+x gradlew
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
